### ISSUE TITLE
How would SObjectDomain work for generic SObject with multiple RecordTypes?

### ISSUE THREAD

**Issue by ghost** [financialforcedev/df12-apex-enterprise-patterns#4]
Hy Andrew,

I have a sobject called Document and many record types. I would like to put common code into an abstract or virtual base class and record type specific things into subclasses. Regarding constructor rules in subclasses (no 0-arg constructor, ....)) I can't get this running.

Have you implemented such a structure? How did you circumvent those problems?

Best regards,

Robert

**Comment by Xtremefaith** [comment]
Now we'll never know the answer :(

I'm hoping that the more this library is adopted the stronger the documentation around it gets. There are some advanced concepts that I think this library helps to adapt, but at times it assumes the concept is already understood. I continue to attempt using some of the exact snippets from the sample library with the addition of the Stub API and get nothing but errors. Trying to do enough leg work before posting an issue, but as stated, feeling like the documentation and samples are not up to date with the current expected use case.

**Comment by afawcett** [comment]
Hi @Xtremefaith this is a very old verison of the library, please check out https://github.com/financialforcedev/fflib-apex-common and the documentation section in the README file. I also have a few chapters in my book that covers this lib and a generic testing chapter. :+1:
